---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.27.2
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3306
        protocol: TCP
